language: node_js
node_js: "10"
cache: yarn

branches:
  only:
  - master
stages:
- test
  
install:
- yarn --ignore-engines
- npm install -g gulp ava typescript
- ./server/scripts/clone-mongo-tools.sh
- ./server/scripts/alias-mongo-tools.sh
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
- gulp defs
- tsc --build --force && tsc -p shared/tsconfig.commonjs.json
- ava --verbose server/test/tests/env.test.js
- yarn test
notifications:
  email:
    on_success: change
    on_failure: change
services:
  - mongodb