language: node_js
node_js: "10"
cache: yarn

branches:
  only:
  - master
stages:
- test
  
install:
- yarn --ignore-engines
- cd server && yarn --ignore-engines && cd ..
- npm install -g gulp ava
- ./server/scripts/clone-mongo-tools.sh
- ./server/scripts/alias-mongo-tools.sh
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
- tsc
- ava --timeout=5m
notifications:
  email:
    on_success: change
    on_failure: change
services:
  - mongodb