language: node_js
node_js: '10'
cache:
  directories:
  - "~/.npm"
  - "~/.cache"
branches:
  only:
  - master
stages:
- test
install:
- yarn --ignore-engines
- npm install -g gulp mocha typescript
- "./server/scripts/clone-mongo-tools.sh"
- "./server/scripts/alias-mongo-tools.sh"
before_script:
- sleep 15
- mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
- gulp precompile
- tsc -v
- tsc --build --force
- tsc --build --force test/tsconfig.json
- mocha test/unit/unit.test.js --exit
- gulp pretest
- node test/ui/test-cypress.js
notifications:
  email:
    on_success: change
    on_failure: change
services:
- mongodb